// Copyright (C) 2026 Industrial Algebra
// SPDX-License-Identifier: AGPL-3.0-only

//! Mingot - The Leptos UI library for applications that demand mathematical precision
//!
//! Mingot provides ultra-precision UI components for scientific computing, financial applications,
//! and mathematical software. Built with first-class support for u64+ precision integers and
//! arbitrary-precision decimals via rust_decimal integration.
//!
//! ## Why Mingot?
//!
//! Most web UI libraries stop at JavaScript's Number type (safe integers up to 2^53 - 1).
//! Mingot goes beyond with:
//!
//! - **NumberInput** supporting u64, u128, i64, i128, and arbitrary precision
//! - **Zero precision loss** throughout the component lifecycle
//! - **Type-safe validation** with detailed error types
//! - **rust_decimal integration** for 128-bit arbitrary-precision decimals (optional)
//!
//! ## Precision Without Compromise
//!
//! ```rust,ignore
//! use mingot::prelude::*;
//!
//! // High-precision number input
//! <NumberInput
//!     precision=NumberInputPrecision::U64
//!     label="Large Integer"
//!     on_valid_change=Callback::new(move |result| {
//!         // Supports values up to 18,446,744,073,709,551,615
//!     })
//! />
//! ```
//!
//! # Quick Start
//!
//! ```rust,no_run
//! use leptos::prelude::*;
//! use mingot::prelude::*;
//!
//! #[component]
//! fn App() -> impl IntoView {
//!     view! {
//!         <MingotProvider>
//!             <Container>
//!                 <Stack spacing="md">
//!                     <Text size=TextSize::Xl weight=TextWeight::Bold>
//!                         "Welcome to Mingot"
//!                     </Text>
//!                     <Button variant=ButtonVariant::Filled on_click=Callback::new(move |_| {})>
//!                         "Click me"
//!                     </Button>
//!                 </Stack>
//!             </Container>
//!         </MingotProvider>
//!     }
//! }
//! ```

//!
//! ## Features
//!
//! Mingot uses additive feature flags. Rendering modes are mutually
//! exclusive at use time; precision and token features are opt-in:
//!
//! - `csr` (default): client-side rendering via Leptos
//! - `ssr`: server-side rendering via Leptos
//! - `hydrate`: hydration for SSR apps
//! - `high-precision`: enables `NumberInputPrecision::Arbitrary` via
//!   [`rust_decimal`](https://docs.rs/rust_decimal) (128-bit, 28-29 significant digits)
//! - `theme-tokens`: serde JSON export/import of design tokens

// `extra_unused_lifetimes` is emitted by clippy on code generated by Leptos's
// `TypedBuilder` derive (via `#[component]`), not on Mingot's own source. It
// cannot be fixed in our code; it is third-party macro noise that began firing
// on nightly >= 1.98. Allow it crate-wide so `-D warnings` stays meaningful for
// lints we can actually act on.
#![allow(clippy::extra_unused_lifetimes)]

pub mod components;
pub mod theme;
pub mod utils;
pub mod validation;

/// Precision-aware node graph editor (Phase 7). Enable with the `node-graph` feature.
#[cfg(feature = "node-graph")]
pub mod node_graph;

// Re-export commonly used components
pub use components::*;
pub use theme::{
    use_color_scheme, use_color_scheme_toggle, use_set_color_scheme, use_theme, ActiveColorScheme,
    ColorSchemeMode, MingotProvider, Theme, ThemeBuilder, ThemeContext, ThemeOverride,
};
pub use validation::{ValidationError, ValidationResult, Validator};

// Re-export leptos for convenience
pub use leptos;

/// Prelude module with commonly used imports
pub mod prelude {
    pub use crate::components::*;
    pub use crate::theme::{
        use_color_scheme, use_color_scheme_toggle, use_set_color_scheme, ActiveColorScheme,
        ColorSchemeMode, MingotProvider, Theme, ThemeBuilder, ThemeOverride,
    };
    pub use crate::validation::{self, ValidationError, ValidationResult, Validator};
}
